{% set name = "dask-image" %}
{% set version = "0.5.0" %}
{% set sha256 = "0bf7ea8dcd9d795505b498bd632394720c048f50761e23c574d9a6bacfb27cbb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools

  run:
    - python >=3.6
    - dask >=0.16.1
    - numpy >=1.11.3
    - scipy >=0.19.1
    - pims >=0.4.1

test:
  source_files:
    - tests

  imports:
    - dask_image

  requires:
    - pytest >=3.0.5
    - scikit-image >=0.12.3,<0.17.0

  commands:
    - pytest

about:
  home: https://github.com/dask/dask-image
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Distributed image processing
  doc_url: https://dask-image.readthedocs.io/
  dev_url: https://github.com/dask/dask-image

extra:
  recipe-maintainers:
    - GenevieveBuckley
    - jakirkham
    - m-albert
